### ISSUE TITLE
Missing required properties for `Create Check Run` in docs

### ISSUE THREAD

**Issue by oscard0m** [octokit/rest.js#108]
**What happened?**
Missing **required** properties for 
```javascript
octokit.rest.checks.create({
  owner,
  repo,
});
```

[According to GitHub Documentation](https://docs.github.com/en/rest/reference/checks#create-a-check-run), `name` and `head_sha` are required body parameters to be passed.

**Minimal test case to reproduce the problem**
You can see the error in Docs' table https://octokit.github.io/rest.js/v18#checks-create

**What did you expect to happen?**
To get the right parameters marked as **required** in docs.

**What the problem might be**
Details here: https://github.com/octokit/plugin-rest-endpoint-methods.js/issues/441

**Comment by oscard0m** [comment]
Tagging @inesilva since we discovered together

**Comment by wolfy1339** [comment]
This should get fixed by https://github.com/octokit/plugin-rest-endpoint-methods.js/pull/694
