### ISSUE TITLE
Getting Error: Empty value for parameter 'tag': undefined

### ISSUE THREAD

**Issue by ravali-rimmalapudi** [octokit/rest.js#121]
**Checklist**

- [x] I checked [all open bugs](https://github.com/octokit/rest.js/issues?q=is%3Aissue+label%3Abug) and none of them matched my problem.

**Environment**

- [x] https://api.github.com
- [ ] GitHub Enterprise Server: 
- [ ] GitHub Enterprise Cloud
- [x] Node.js
- [ ] Browsers: 
- [ ] Others: 

**Versions**
```
"@actions/core": "^1.0.0",
"@actions/github": "^2.2.0",
"@octokit/rest": "^18.10.0",
```

**What happened?**
getWorkflow method is giving error: `Error: Empty value for parameter 'tag': undefined`

**Minimal test case to reproduce the problem**

```
const workflow = await octokit.rest.actions.getWorkflow({
      owner,
      repo,
      workflow_id: workflowName
    });
```
This API is returning the workflow details but it's giving the error also.

**What did you expect to happen?**

The API should return workflow details without any errors.

**What the problem might be**

**Comment by gr2m** [comment]
Hi Ravali, I tried to reproduce the problem but no luck:
https://runkit.com/gr2m/octokit-rest-js-121

My guess is that the error originates somewhere else.The "Get a workflow" endpoint does not have a `tag` parameter:
https://docs.github.com/en/rest/reference/actions#get-a-workflow

**Comment by ravali-rimmalapudi** [comment]
Thanks for the response. Yes, you are correct, Error is coming from some other place.
