### ISSUE TITLE
how to handle 404, next js throw a HTTP 500 ?

### ISSUE THREAD

**Issue by sajrashid** [octokit/rest.js#129]
Hi,

**Environment**
- [  "nextjs": "11.1.2",next-auth: 3.27.3] 

**Versions**
├── @octokit/auth-app@3.6.1
├── @octokit/core@3.5.1

**What happened?**

When requesting to the workflows [API](https://docs.github.com/en/rest/reference/actions#list-repository-workflows),  GitHub returns a 404 if there are no workflows. Octokit then throws an error from  @octokit\request\dist-node\index.js:86. Then next-js throws an HTTP 500, I've tried to redirect the error back to a 404 but am unable to trap the error, with Octokit or Fetch or Try/Catch.

Is there a workaround that I can use to prevent the HTTP 500?

`    if (status >= 400) {
      const data = await getResponseData(response);
      const error = new requestError.RequestError(toErrorMessage(data), status, {
        response: {
          url,
          status,
          headers,
          data
        },
        request: requestOptions
      });
      throw error;
    }`

error - RequestError [HttpError]: Not Found
    at C:\Users\Me\source\repos\my-nextauth-twitter\node_modules\@octokit\request\dist-node\index.js:86:21    at runMicrotasks (<anonymous>)

**Minimal test case to reproduce the problem**
This is a GitHub App, it will take me some time to get a live version running, can we do this if there is no workaround, or if it's a real issue?

**What did you expect to happen?**
Expect to be able to handle error

Thanks.

**Comment by G-Rath** [comment]
404 is a valid response for us to be returning - we're not responsible for what happens after that, so you should be reporting this as a bug with Next since that's what's turning it into a 500 :)
