### ISSUE TITLE
[Typescript] Octokit "auth" option does not support example from docs for installation tokens

### ISSUE THREAD

**Issue by douglascayers** [octokit/rest.js#13]
I recently updated the following octokit modules and began receiving a deprecation warning about not providing an `authStrategy`.

## Deprecation Warning
> Setting the "new Octokit({ auth })" option to an object without also setting the "authStrategy" option is deprecated and will be removed in v17. See (https://octokit.github.io/rest.js/#authentication)

## Octokit Modules
```json
"@octokit/app": "4.1.1",
"@octokit/auth-app": "2.4.2",
"@octokit/plugin-retry": "3.0.1",
"@octokit/plugin-throttling": "3.2.0",
"@octokit/rest": "16.40.1",
"@octokit/webhooks": "7.0.0",
```

## Code That Raises Deprecation Warning

```js
import OctokitRest from '@octokit/rest';

const client = new OctokitRest({
    async auth(): Promise<string> {
        const token = await app.getInstallationAccessToken({
            installationId: MY_INSTALLATION_ID,
        });
        return `token ${token}`;
    },
    ...
});
```

## Code I Would Like To Use

```js
import { createAppAuth } from '@octokit/auth-app';
import OctokitRest from '@octokit/rest';

const client = new OctokitRest({
    authStrategy: createAppAuth,
    auth: {
        id: MY_APP_ID,
        privateKey: MY_PRIVATE_KEY,
        installationId: MY_INSTALLATION_ID
    },
    ...
});
```

## Discrepancy to Documentation

Per the [example](https://octokit.github.io/rest.js/#authentication) in the documentation, I should be able to specify the app `id` and `privateKey` as the `auth` settings but those are not valid per the [current typescript definition](https://raw.githubusercontent.com/octokit/rest.js/master/index.d.ts).

![image](https://user-images.githubusercontent.com/4142577/73334668-f128c380-4232-11ea-8bfc-67d07a557b6c.png)

## Proposal

Not sure if this is on your [roadmap to v17](https://github.com/octokit/rest.js/issues/1546), but if not then here's my two cents.

Since the octokit rest module's [authentication plugin](https://github.com/octokit/rest.js/blob/master/plugins/authentication/index.js#L18) just passes `options.auth` to the auth strategy via `const auth = options.authStrategy(options.auth);`, should the typescript definition for `auth` in this octokit rest module match [StrategyOptions](https://github.com/octokit/auth-app.js/blob/master/src/types.ts#L75) type as shown in the [auth-app usages](https://github.com/octokit/auth-app.js#usage)?

Thanks!

**Comment by gr2m** [comment]
closing in favor of https://github.com/octokit/core.js/issues/323

**Comment by duynguyen0209** [comment]
V
