### ISSUE TITLE
Add Option for Get Content to Return Buffer

### ISSUE THREAD

**Issue by iddan** [octokit/rest.js#137]
**What’s missing?**

The ability to get a buffer from `getContent()`

**Why?**

The conversion from base64 is costly and unnecessary

**Alternatives you tried**

I tried to call `request()` my self but still didn't have the ability to get the result as Buffer instead of string

With fetch it is possible:
```javascript
const res = await fetch(
  `GET /repos/${owner}/${repo}/contents/${path}`,
  {
    headers: {
      accept: "application/vnd.github.v3.raw",
      // requires authorization here
      authorization: "",
    },
  }
);

const buffer = await res.arrayBuffer()
```

**Comment by wolfy1339** [comment]
This has been implemented in `@octokit/request`.

You simply have to modify your call like so,
```js
octokit.rest.repos.getContent({
  owner,
  repo,
  path,
  request: {
    parseSuccessResponseBody: false
  }
});
```
