### ISSUE TITLE
Listing pull requests should return conflict state

### ISSUE THREAD

**Issue by EvanBurbidge** [octokit/rest.js#138]
**Mergable state**

In the octokit graphql client I'm able to fetch the mergable state of individual pull requests. This does not exist in the rest version of this api.

**Why?**

In our current application we call the merge api, however we need that button blocked if there are conflicts. We'd also like to display the fact that there are conflicts. 

An alternative we've tried is calling individual pull requests via the api to try find this state but this is causing latency issues.

**Comment by wolfy1339** [comment]
This library is only a wrapper around GitHub's REST api, we cannot add any new features or data.

Your best bet is to contact support and suggest the idea.

**Comment by EvanBurbidge** [comment]
Will do thanks! :)
