### ISSUE TITLE
[TypeScript] access parameters/responses subtypes

### ISSUE THREAD

**Issue by ianwremmel** [octokit/rest.js#1697]
I've been making use of the types `AppsListAccountsUserOrOrgOnPlanResponse`, `AppsListAccountsUserOrOrgOnPlanResponseItem`, and `AppsListAccountsUserOrOrgOnPlanResponseItemMarketplacePurchasePlan`.

With V17, I can do 
```ts
export type AppsListAccountsUserOrOrgOnPlanResponse = RestEndpointMethodTypes['apps']['listAccountsUserOrOrgOnPlan']['response']['data'];
```
But to get to the subtypes, I need to do 

```ts
export type AppsListAccountsUserOrOrgOnPlanResponse = RestEndpointMethodTypes['apps']['listAccountsUserOrOrgOnPlan']['response']['data'];
export type AppsListAccountsUserOrOrgOnPlanResponseItem = AppsListAccountsUserOrOrgOnPlanResponse[0];
export type AppsListAccountsUserOrOrgOnPlanResponseItemMarketplacePurchasePlan = AppsListAccountsUserOrOrgOnPlanResponseItem['marketplace_purchase']['plan']
```

In articular, the `AppsListAccountsUserOrOrgOnPlanResponse[0]` seems strange.

**Comment by gr2m** [comment]
Sorry Ian for not getting back to you. My time for Octokit is very limited, and I don't have a good answer. But I do agree that the current solution is not sufficient.

I am considering to export the types similar to how they have been exported in v16. I'm not quite sure what the right approach would be, maybe export a`Octokit` namespace with an `Endpoints` interface on it, which would then have all the different keys for requests and responses on it? 

Can you think of a project similar to Octokit which does a good job with that? Or anyone I could reach out to for help?
