### ISSUE TITLE
improve ESM compatibility by using fully qualified file names with extension

### ISSUE THREAD

**Issue by arlac77** [octokit/rest.js#17]
On the long journey to native ESM modules (for all engines) one step would be the use of
fully qualified imports (with .js | .mjs extension)

```js
import { VERSION } from "./version.mjs";
```

any opinions ?

**Comment by gr2m** [comment]
The proper solution to this will be to publish native ES Modules to npm, now that Node has a full specification for it. 

This will be a bigger project, but I'll get this process started soon. Given that Octokit is also supporting browsers and deno, both of with natively support ESM, and that starting May all supported Node versions do, too, it makes sense go all in on ESM.

**Comment by gr2m** [comment]
I cannot reproduce a problem when using native ESM with Node.

Here is my `package.json`

```json
{
  "name": "test",
  "type": "module",
  "dependencies": {
    "@octokit/rest": "^18.5.3"
  }
}
```

and `index.js`

```js
import { Octokit } from "@octokit/rest";

const octokit = new Octokit({
  auth: process.env.GITHUB_TOKEN,
});

run();

async function run() {
  const { data: user } = await octokit.request("GET /user");
  console.log(user);
}
```

This runs in latest node 12, 14, 15, and 16.

We can still do better by publishing native ES modules ourselves, but we'll get there eventually.

Can we close this issue?

**Comment by arlac77** [comment]
Yes please, looking forward for the native ESM future
