### ISSUE TITLE
Feature suggestion: add new Issues method, to add issue to project board

### ISSUE THREAD

**Issue by jeherve** [octokit/rest.js#181]
**What’s missing?**

There is currently no easy way (short of relying on the GraphQL API) to automatically add an issue to a GitHub project board.

**Why?**

Ideally, I think it would be nice if we had another method to `octokit.rest.issues`, allowing one to add a given issue to a specific project board (and project board column). This would be somewhat similar to `addAssignees` or `addLabels`, and would give an easy option to link an issue to a project in one go.

**Alternatives you tried**

As far as I know, `octokit.graphql` is currently the only way to achieve something like this. This is covered here:
https://docs.github.com/en/issues/planning-and-tracking-with-projects/automating-your-project/using-the-api-to-manage-projects

**Comment by wolfy1339** [comment]
Thanks for the great suggestion!

However, we do not control GitHub's API.
We only provide methods to use the API.

You should contact support to tell them about this new feature.

**Comment by jeherve** [comment]
Ok, thanks for the quick reply!

> You should contact support to tell them about this new feature.

For anyone who may stumble across this issue, I posted here about it:
https://github.com/community/community/discussions/27480

**Comment by gr2m** [comment]
In case you want to add issues to the new projects (which I think will eventually replace the current projects), you can use https://github.com/gr2m/github-project/. They have board views, too.

**Comment by jeherve** [comment]
@gr2m Thank you! I'll definitely look at that repo, it seems to be a great way to interact with projects. 👍 🌟
