### ISSUE TITLE
Thank you everyone who has helped this code become what it is today

### ISSUE THREAD

**Issue by jeffkeen** [octokit/rest.js#1835]
**Checklist**

- [ ] I checked [all open bugs](https://github.com/octokit/rest.js/issues?q=is%3Aissue+label%3Abug) and none of them matched my problem.

**Environment**

- [ ] https://api.github.com
- [ ] GitHub Enterprise Server: 
- [ ] GitHub Enterprise Cloud
- [ ] Node.js
- [ ] Browsers: 
- [ ] Others: 

**Versions**

**What happened?**

**Minimal test case to reproduce the problem**

**What did you expect to happen?**

**What the problem might be**

**Comment by gr2m** [comment]
Thank you ❤️
