### ISSUE TITLE
listEventsForTimeline returns  RequestError [HttpError] If you would like to help us test the Timeline API during its preview period, you must specify a custom media type in the 'Accept' header. Please see the docs for full details.

### ISSUE THREAD

**Issue by MohamedBengezi** [octokit/rest.js#184]
**Checklist**

- [X] I checked [all open bugs](https://github.com/octokit/rest.js/issues?q=is%3Aissue+label%3Abug) and none of them matched my problem.

**Environment**

- [ ] https://api.github.com
- [X] GitHub Enterprise Server: 3.1.2.2
- [ ] GitHub Enterprise Cloud
- [ ] Node.js
- [ ] Browsers: 
- [ ] Others: 

**Versions**

├── @octokit/rest@18.12.0

**What happened?**

When attempting to run: 
```
 var page = await context.octokit.issues.listEventsForTimeline({
  owner,  // Db2
  repo: context.payload.repository.name, // db2
  issue_number: pull_number, 
  per_page: 100,
  page: page_num,
});
```
I get the following error: 
```
 RequestError [HttpError]: If you would like to help us test the Timeline API during its preview period, you must specify a custom media type in the 'Accept' header. Please see the docs for full details.
    at /Users/mohamedbengezi/db2-tracker-mgr/node_modules/@octokit/request/dist-node/index.js:86:21
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async sendRequestWithRetries (/Users/mohamedbengezi/db2-tracker-mgr/node_modules/@octokit/auth-app/dist-node/index.js:376:12)
    at async Job.doExecute (/Users/mohamedbengezi/db2-tracker-mgr/node_modules/bottleneck/light.js:405:18) {
  status: 415,
  response: {
    url: 'https://github.ibm.com/api/v3/repos/DB2/db2/issues/20753/timeline',
    status: 415,
    headers: {
      'access-control-allow-origin': '*',
      'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset',
      connection: 'close',
      'content-length': '307',
      'content-security-policy': "default-src 'none'",
      'content-type': 'application/json; charset=utf-8',
      date: 'Tue, 09 Aug 2022 18:26:02 GMT',
      'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
      server: 'openresty',
      'strict-transport-security': 'max-age=31536000; includeSubdomains',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'deny',
      'x-github-enterprise-version': '3.1.22',
      'x-github-media-type': 'github.v3; param=json-preview; format=json',
      'x-github-request-id': '677e3c9a-f061-4fa6-ba90-b7dacc9bfdc4',
      'x-ratelimit-limit': '5000',
      'x-ratelimit-remaining': '4995',
      'x-ratelimit-reset': '1660073147',
      'x-runtime-rack': '0.055794',
      'x-xss-protection': '1; mode=block'
    },
    data: {
      message: "If you would like to help us test the Timeline API during its preview period, you must specify a custom media type in the 'Accept' header. Please see the docs for full details.",
      documentation_url: 'https://docs.github.com/enterprise/3.1/rest/reference/issues#list-timeline-events-for-an-issue'
    }
  },
  request: {
    method: 'GET',
    url: 'https://github.ibm.com/api/v3/repos/DB2/db2/issues/20753/timeline',
    headers: {
      accept: 'application/vnd.github.json-preview+json',
      'user-agent': 'probot/12.2.5 octokit-core.js/3.6.0 Node.js/17.0.1 (darwin; x64)',
      authorization: 'token [REDACTED]'
    },
    request: {
      hook: [Function: bound bound register],
      retryCount: 3,
      retries: 3,
      retryAfter: 16
    }
  }
}
```
 
I tried also using `octokit.request` and `octokit.paginate` but both failed with the same problem. It was working initially (a month or two ago), but hasn't been working since. 

You can reproduce it by running `octokit.issues.listEventsForTimeline()`.

**What did you expect to happen?**

it should return an object that has a property containing the list of timeline events for the specific issue. 

**What the problem might be**

Something additional is required in the accept headers, but it doesn't specify what exactly it looks for.

**Comment by timrogers** [comment]
Hi there! 👋 Thanks for reaching out. It looks like you need to set the `Accept` header to `application/vnd.github.mockingbird-preview`, judging by the docs - previews like this no longer exist on GitHub.com, but they are still present in your Enterprise Server version. 

Can you try specifying that using a `headers` property in your function call?

**Comment by wolfy1339** [comment]
You will need to add the proper preview needed as specified in the [docs](https://docs.github.com/en/enterprise-server@3.1/rest/issues/timeline#list-timeline-events-for-an-issue-preview-notices)
```js
const page = await context.octokit.issues.listEventsForTimeline({
  owner,
  repo: context.payload.repository.name,
  issue_number: pull_number, 
  per_page: 100,
  page: page_num,
  mediaType: {
    previews: ['mockingbird']
  }
});
```
https://octokit.github.io/rest.js/v18#previews

**Comment by timrogers** [comment]
> You will need to add the proper preview needed as specified in the [docs](https://docs.github.com/en/enterprise-server@3.1/rest/issues/timeline#list-timeline-events-for-an-issue-preview-notices)
> 
> ```js
> 
> const page = await context.octokit.issues.listEventsForTimeline({
> 
>   owner,
> 
>   repo: context.payload.repository.name,
> 
>   issue_number: pull_number, 
> 
>   per_page: 100,
> 
>   page: page_num,
> 
>   mediaType: {
> 
>     previews: ['mockingbird']
> 
>   }
> 
> });
> 
> ```
> 
> https://octokit.github.io/rest.js/v18#previews

Thanks for the better answer than mine! I was on my phone and didn't check the readme 😅 Better to use this rather than custom headers if you can.

**Comment by MohamedBengezi** [comment]
Ahhh yeah that did it @timrogers . Thanks so much to both you and @wolfy1339 . This issue can be closed now

P.S. I commented on the wrong issue before, cant seem to find the issue number now
