### ISSUE TITLE
Cannot delete gist file with filename: null

### ISSUE THREAD

**Issue by UziTech** [octokit/rest.js#19]
according to the [documentation](https://developer.github.com/v3/gists/#edit-a-gist)
> To delete a file, set the value of the filename to `null`.

This gives the error `Invalid request. For 'properties/filename', nil is not a string.`

```js
octokit.gists.update({
  "gist_id": [REDACTED],
  "files": {
    "README": {
      "filename": null
    }
  }
})
```

**Comment by gr2m** [comment]
I'm now getting a 404 🤷🏼 

```
curl -X PATCH -H"Authorization: token ghp_[REDUCTED PAT WITH GIST SCOPE]" https://api.github.com/gists/9f00c3cef38a7db78ee5c26da9f6db89 -d '{"files":{"test.md":{"content":null}}}' 
{
  "message": "Not Found",
  "documentation_url": "https://docs.github.com/rest/reference/gists#update-a-gist"
}
```

I'll ask support, the docs no longer mention how to delete a file in a gist, unless I'm missing something

**Comment by gr2m** [comment]
I got a response from support. To delete a file, leave out the `content` key instead of setting it to `null`.

Here is their response in full

> It looks like we definitely need to update our documentation for this endpoint. I'm going to open an issue for Documentation team. I've also checked the underlying code to determine what the API is expecting, I'll explain how to use the endpoint below.
> 
> To *delete* a file from a Gist, you must still provide it in the `files` object, but `content` should be empty or not specified. I'll include an example below, first to create a Gist with two files:
> 
> ```
> curl -X POST 'https://api.github.com/gists' -H 'Authorization: Bearer token' -H 'Content-Type: text/plain' --data-raw '{"description":"Gists API testing", "public":true, "files":{"helloworld.md":{"content":"Hello"}, "deleteme.md":{"content":"Delete me"}}}'
> 
> ```
> 
> And then to delete `deleteme.md`:
> 
> ```
> curl -X PATCH 'https://api.github.com/gists/cbaf6495909cc85d0168b975018b7c56' -H 'Authorization: Bearer token' -H 'Content-Type: text/plain' --data-raw '{"description":"Gists API testing", "public":true, "files":{"deleteme.md":{}}}'
> 
> ```
> 
> You can see what that looks like in the UI here:
> 
> <https://gist.github.com/stevecat/cbaf6495909cc85d0168b975018b7c56/revisions>
> 
> To rename a Gist, you can provide an extra `filename` field with the new filename. You *can* provide `content` here too, if you also need to update that. Here's an example that renames a file called "renameme.md" to "renamed.md".
> 
> ```
> curl -X PATCH 'https://api.github.com/gists/d0a5bdc1fc76b1de779dfe5fe87610f2' -H 'Authorization: Bearer token' -H 'Content-Type: text/plain' --data-raw '{"description":"Gists API testing", "public":true, "files":{"renameme.md":{"filename":"renamed.md"}}}'
> 
> ```
> 
> And we can see how that looks here:
> 
> <https://gist.github.com/stevecat/d0a5bdc1fc76b1de779dfe5fe87610f2/revisions>

**Comment by gr2m** [comment]
I'll close the issue as there is nothing actionable for us to do. Once the docs get updated the docs for `@octokit/rest` will get updated automatically
