### ISSUE TITLE
delete branch (git.deleteRef) fails with 500 in GitHub actions

### ISSUE THREAD

**Issue by harryparkdotio** [octokit/rest.js#190]
**Checklist**

- [x] I checked [all open bugs](https://github.com/octokit/rest.js/issues?q=is%3Aissue+label%3Abug) and none of them matched my problem.

**Environment**

- [x] https://api.github.com
- [x] Node.js 18

**Versions**

```
octokit@2.0.4
```

**What happened?**

When calling `octokit.rest.git.deleteRef` to delete a branch, the request returns a 500 error when running from within a GitHub action.

Interestingly, the request succeeded when running from my machine locally, but repeatedly fails when running inside of a GitHub action.

---

branch name: `chore/my-branch`

```
error: {
      "type": "RequestError",
      "message": "fetch failed",
      "stack":
          HttpError: fetch failed
              at /home/runner/work/.../node_modules/@octokit/request/dist-src/fetch-wrapper.js:96:15
              at async Job.doExecute (/home/runner/work/.../node_modules/bottleneck/light.js
      "name": "HttpError",
      "status": 500,
      "request": {
        "method": "DELETE",
        "url": "https://api.github.com/repos/org/repo/git/refs/heads%2Fchore%2Fmy-branch",
        "headers": {
          "accept": "application/vnd.github.v3+json",
          "user-agent": "... octokit.js/2.0.4 octokit-core.js/4.0.4 Node.js/18.7.0 (linux; x64)",
          "authorization": "token [REDACTED]",
          "content-length": 0
        },
        "request": {
          "retryCount": 3,
          "retries": 3,
          "retryAfter": 16
        }
      }
    }
```

**Minimal test case to reproduce the problem**

```ts
await octokit.rest.pulls.update({
    owner: config.org,
    repo: config.repo,
    pull_number: pr.number,
    state: 'closed',
  });

  await octokit.rest.git
    .deleteRef({
      owner: config.org,
      repo: config.repo,
      ref: `heads/${pr.head.ref}`,
    })
    .catch((err) => {
      logger.error(
        { error: err },
        `PR #${pr.number}: failed to delete pull request branch`
      );
    });
```

**What did you expect to happen?**

expected `octokit.rest.git.deleteRef` to successfully delete a branch.

**What the problem might be**

Could be that octokit is not actually making the request, since no response object exists.

---

not sure if relevant, but I'm closing the pr (successfully) before attempting to delete the branch.

again this succeeds when run from my local machine, but fails when run from within GitHub actions.

---

I've reached out to GitHub support, but I was unable to get a `X-GitHub-Request-Id` for the request. Support suggested that I instead raise an issue here.

**Comment by timrogers** [comment]
Thanks for the detailed bug report! I suspect this is related to https://github.com/octokit/request.js/issues/506.

**Comment by timrogers** [comment]
You'd be able to work around this for now by using an earlier Node.js version without native fetch.
