### ISSUE TITLE
Feature request: allow setting owner/repo on the client object

### ISSUE THREAD

**Issue by retorquere** [octokit/rest.js#2]
I usually connect to a single repo; it would be convenient (for me at least) if I could do something like

```js
const github = new GitHubApi({
  debug: true,
  owner: 'retorquere',
  repo: 'zotero-better-bibtex',
})

...

github.issues.get({
  // implicit owner: github.config.owner if owner: is not provided explicitly,
  // implicit repo: github.config.repo if repo: is not provided explicitly,
  number: 852
})
```

**Comment by gr2m** [comment]
This is out of scope for `@octokit/rest` now. But it would be possible to implement as a plugin, similar to https://github.com/octokit/plugin-rest-endpoint-methods.js/. Or as an entirely separate SDK which would only provide APIs for a single repository
