### ISSUE TITLE
Create a pull request in fork A from fork B

### ISSUE THREAD

**Issue by kaovilai** [octokit/rest.js#222]
**What’s missing?**
Looking at https://octokit.github.io/rest.js/v19#pulls-create there doesn't seem to be a way to create pull request from fork to fork.

**Why?**
It's needed to be done

**Alternatives you tried**
Could probably do some CLI hacks or other alternative in the interim.

**Comment by gr2m** [comment]
does GitHub itself support this feature? I think only if fork B is a fork from A

**Comment by kaovilai** [comment]
Yes. eg. https://github.com/openshift/velero/pull/206
is a fork to fork PR.

**Comment by kaovilai** [comment]
@gr2m An example of fork to fork demo.
https://github.com/gr2m/fetch-mock/pull/1

Both are forks of https://github.com/wheresrhys/fetch-mock

**Comment by gr2m** [comment]
try to set `head` to `username:branch`. 

Basically we can't add features that the API doesn't support. If the REST API can do it, then `@octokit/rest` can do it. See the docs for the REST API at https://docs.github.com/en/rest/pulls/pulls#create-a-pull-request

**Comment by kaovilai** [comment]
Resolved. It is possible with current library.
Had to make some changes in the actions I consumed.
https://github.com/tgymnich/fork-sync/compare/master...b89779a787cb24445234ef510636f517a4bcaa02#diff-7934bf411fea192ad8cd69e0a12911648a2842cb0f2409a8fb67b41b7069d757R68
