### ISSUE TITLE
[FEAT]: Add api to access linked issues to a pull request

### ISSUE THREAD

**Issue by fidou** [octokit/rest.js#235]
### Describe the need

I would like to access the issues linked to a pull request and also be able to link an issue. I unable to find anything in the documentation regarding this. I am not even sure the api allows accessing the linked items.

### SDK Version

latest

### Relevant log output

NA

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wolfy1339** [comment]
This isn't the proper place to request new API endpoints.

This module is only a wrapper around the GitHub API, we can't create new APIs.

You will have to reach out to GitHub in order to suggest this new API.

You can suggest that over here: https://github.com/orgs/community/discussions

**Comment by yCodeTech** [comment]
As Octokit is maintained by GitHub itself, then you can surely pass this on to the API team internally...

Unfortunately the discussions is just not that great for suggesting any kind of new feature, or feedback, as they are rarely seen or commented on by GitHub staff and developers (from what I've seen).

I am also looking for this exact API endpoint so I can reliably retrieve the linked issues that will be/have been closed from a pull request, and vice-versa. At the moment, I am using regex to find a closing keywords reference number in the PR description and using the API to retrieve that issue data. This is not ideal and can have a lot of overhead especially if there's many references to verify, and may not be truly reliable.

**Comment by G-Rath** [comment]
Octokit is primarily maintained by volunteers like @wolfy1339 and (to a lesser extent these days) myself, who have little to no direct or special contact with anyone at GitHub
