### ISSUE TITLE
Adding the docs URL directly to the repo URL?

### ISSUE THREAD

**Issue by jeffwilcox** [octokit/rest.js#256]
Hi,
Would it be possible to add the Octokit REST docs (https://github.com/octokit/rest.js/) as the website for the repository, to make navigation from the GitHub repo into the docs easier?

Just a small nit/question/idea.

Thanks,
Jeff

**Comment by kfcampbell** [comment]
Hi Jeff! Did you mean https://octokit.github.io/rest.js/v19 ? I've changed the repo URL to reflect that. Please let me know if that's correct!

**Comment by jeffwilcox** [comment]
Yes. Thank you so much 🎉
