### ISSUE TITLE
[DOCS]: Contributing update for tweetsodium (deprecated) example code

### ISSUE THREAD

**Issue by davidcarboni** [octokit/rest.js#264]
### Describe the need

Hi there, I noticed the docs still seem to have example code that encrypts secrets using tweetsodium which is deprecated.

I've just implemented an update in my own code to use libsodium.js so I thought I'd pass on the (small) changes:

```
const libsodium = require('libsodium-wrappers');

const key = "base64-encoded-public-key";
const value = "plain-text-secret";

// Convert the message and key to Uint8Array's (Buffer implements that interface)
const messageBytes = Buffer.from(value);
const keyBytes = Buffer.from(key, 'base64');

// Encrypt using LibSodium.
const encryptedBytes = libsodium.crypto_box_seal(messageBytes, keyBytes);

// Base64 the encrypted secret
const encrypted = Buffer.from(encryptedBytes).toString('base64');

console.log(encrypted);

```

I've been looking for a solution for a while so thought I'd share. 
The code above is adapted from the Tweetsodium readme: https://github.com/github/tweetsodium

Hope this is helpful!

### SDK Version

Octokit rest

### API Version

v19

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kfcampbell** [comment]
@davidcarboni do you have any interest in opening up a PR for this docs change yourself?

**Comment by davidcarboni** [comment]
Sure! Happy to give that a go. Let me see if I can get that done.

**Comment by davidcarboni** [comment]
Hi there, I've forked and cloned the repo but I'm struggling to find where I would need to make an edit?

I've browsed under the /docs directory and have tried a global search search for any mention of "tweetsodium", "sodium" or "encrypt" by my vscode is saying there are no matches.

I've been able to get the documentation running locally and I can see the part I'd like to update, but I can't figure out where that corresponds to in the source code.

I thought I'd reach out and ask. Hopefully I'm missing something obvious - I thought it would be a quick edit and PR but I seem to be stuck!

Many thanks
David

**Comment by kfcampbell** [comment]
Hmm...I've just replicated those steps and I'm just as confused as you are! Where are you seeing the docs that referenced tweetsodium before?

**Comment by wolfy1339** [comment]
I believe the aforementioned docs, are the JSDoc comments on the [`octokit.rest.actions.createOrUpdateOrgSecret()`](https://octokit.github.io/rest.js/v19#actions-create-or-update-org-secret) method.

Those docs aren't coming from octokit, and come from GitHub.
You'll be better off opening an issue with them at the following repo: https://github.com/github/rest-api-description/

**Comment by wolfy1339** [comment]
Closing as this isn't an issue with Octokit
