### ISSUE TITLE
"See also" links points to the developer.github.com instead of docs.github.com

### ISSUE THREAD

**Issue by 3cpt** [octokit/rest.js#29]
**Checklist**

- [x] I checked [all open bugs](https://github.com/octokit/rest.js/issues?q=is%3Aissue+label%3Abug) and none of them matched my problem.

**Environment**

- [x] Others: https://octokit.github.io/rest.js/

**Versions**

V18 (Current - https://octokit.github.io/rest.js/)

**What happened?**

"See also" links points to the developer.github.com instead of docs.github.com. This can lead us to out dated documentation

**Minimal test case to reproduce the problem**

- Go to https://octokit.github.io/rest.js/v18#repos-get-community-profile-metrics
- Click on the `See also: GitHub Developer Guide documentation.`

**What did you expect to happen?**

Redirects to the new documentation

**What the problem might be**

Map all the links of the old documentation with the new

**Comment by gr2m** [comment]
This has been resolved
