### ISSUE TITLE
[BUG]: Could not find a declaration file for module '@octokit/request'

### ISSUE THREAD

**Issue by Stono** [octokit/rest.js#296]
### What happened?

Using the latest version of `@octokit/rest` (19.0.8), I get:

```
node_modules/@octokit/core/dist-types/index.d.ts(2,25): error TS7016: Could not find a declaration file for module '@octokit/request'. '/Users/Karl.Stoney/git/autotrader/node-at-github/node_modules/@octokit/request/dist-node/index.js' implicitly has an 'any' type.
```

During the build.

I was on `19.0.7` and got the same thing, which built previously fine.  Therefore this feels like a transitive dependency issue?

### Versions

19.0.8

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stono** [comment]
This is "Fixed" by explicitly installing an older version of `@octokit/request`;

```
npm i --save @octokit/request@6.2.3
```

**Comment by wolfy1339** [comment]
This should be fixed now. Can you try updating your lcokfiles, or reinstalling the package?

If that doesn't work, I can push an update that bumps the dependencies so you get a fixed version
