### ISSUE TITLE
CDN Bug

### ISSUE THREAD

**Issue by realpxd** [octokit/rest.js#298]
**Everything was working fine recently** _but today's morning all of a sudden , The project am working on stopped working !_

**Am receiving the following error in the console :-** 
`Uncaught SyntaxError: The requested module '/-/@octokit/plugin-rest-endpoint-methods@v7.1.2-oh7as98dHhwO9RAmSS7b/dist=es2019,mode=imports/optimized/@octokit/plugin-rest-endpoint-methods.js' does not provide an export named 'RestEndpointMethodTypes'`

Can you guide me what should I do to fix this problem.

**Comment by TTitcombe** [comment]
I'm also experiencing this and in the process of debugging it.
A new patch version was released a few hours ago, so maybe try rolling back to the previous patch?

**Comment by realpxd** [comment]
If such condition occurs frequently then I will have to switch the product. This one is a major bug, preventing the app to work as intended !

**Comment by RatebSeirawan** [comment]
+

**Comment by wolfy1339** [comment]
Sorry folks, this one's one me. We are switching build systems and we have to explicitly mark every import of types, and re-exports.

I must have missed this one.

**Comment by realpxd** [comment]
> Sorry folks, this one's one me. We are switching build systems and we have to explicitly mark every import of types, and re-exports.
> 
> I must have missed this one.

No worries buddy   &nbsp; : )

**Comment by gr2m** [comment]
> we have to explicitly mark every import of types, and re-exports

is there a way we could verify that we do that correctly as part of our CI?

**Comment by wolfy1339** [comment]
I don't know of a way to do so currently. Doing a dry-run of the build process can point some of them out because they won't exist in JS code, since they are only TS types
