### ISSUE TITLE
[MAINT]: Breaking change released under a patch version

### ISSUE THREAD

**Issue by JoaoBGusmao** [octokit/rest.js#318]
### Describe the need

I'm sadly tied to node 14 due to the complexity to update to node 18.
I'm using lerna, that installs `@octokit/rest`, that installs `@octokit/plugin-paginate-rest`.
`@octokit/plugin-paginate-rest` 6 to 7 introduced a breaking change related to node version, and this library [just updated](https://github.com/octokit/rest.js/commit/a860845b8dd115d18fa93699f0be721abc6c4ec5) from 6.1.2 to 7.0.0 but published this change to 19.0.12 instead of 20.x.
It should have been published under 20.x as this change inherits the breaking change from `@octokit/plugin-paginate-rest`

### Relevant log output

```shell
➜  libs yarn add lerna@6.4.1
yarn add v1.22.19
[1/4] 🔍  Resolving packages...
warning lerna > @lerna/bootstrap > @npmcli/arborist > @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs
warning lerna > @lerna/create > pacote > cacache > @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs
warning lerna > @lerna/bootstrap > @npmcli/arborist > readdir-scoped-modules@1.1.0: This functionality has been moved to @npmcli/fs
[2/4] 🚚  Fetching packages...
error @octokit/plugin-paginate-rest@7.1.2: The engine "node" is incompatible with this module. Expected version ">= 18". Got "14.17.6"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by colinperepelken** [comment]
As a current workaround, we are installing lerna at version 5.1.8 instead, as lerna bumped `@octokit/rest` from v18 -> v19 in 5.2.0

**Comment by gavacq** [comment]
We're still seeing this error, but from another octokit package:
`error @octokit/request-error@4.0.2: The engine "node" is incompatible with this module. Expected version ">= 18". Got "14.21.3"`

**Comment by wolfy1339** [comment]
Missed that one. Filed a bug, and will get to working on it ASAP https://github.com/octokit/request.js/issues/596

**Comment by wolfy1339** [comment]
@gavacq It should be reverted now. It should be the last of `em to revert

**Comment by gavacq** [comment]
Confirmed I can install `lerna@5` on node 14 now. Thanks!
