### ISSUE TITLE
[BUG]: Gists create endpoint  "Resource not accessible by integration"

### ISSUE THREAD

**Issue by carlos-ss** [octokit/rest.js#325]
### What happened?

When attempting to create a gist using `await octokit.rest.gists.create({...})` the internal request fails as a 403 with the response 
data: {
      message: 'Resource not accessible by integration',
      documentation_url: 'https://docs.github.com/rest/reference/gists#create-a-gist'
}

I have added the permissions described in the [doc](https://docs.github.com/en/rest/overview/permissions-required-for-github-apps?apiVersion=2022-11-28#user-permissions-for-gists).

The permission config was tested by using `await octokit.rest.gists.list()` 
When permission is set to 'No access" the request data is just an empty array 
When permission for the Gists is set to 'Read and Write' , I get gists previously created

I get the same results making a postman request directly to the [api](https://docs.github.com/en/rest/gists/gists?apiVersion=2022-11-28#create-a-gist) 

### Versions

@octokit/rest 19.0.13
Node 19.9.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kfcampbell** [comment]
@carlos-ss thanks for the report! API bugs should be filed at our [rest-api-description](https://github.com/github/rest-api-description) repository.

**Comment by carlos-ss** [comment]
Sounds good, TY

**Comment by kfcampbell** [comment]
@carlos-ss I accidentally mislead you; you should go [here](https://github.com/orgs/community/discussions/categories/api-and-webhooks) instead to report API bugs, sorry!
