### ISSUE TITLE
[BUG]: [Package Error] "@octokit/core@v5.0.0" could not be built

### ISSUE THREAD

**Issue by BlakeDarrow** [octokit/rest.js#327]
### What happened?

Looks like the package could not be built. I have had no previous issues using "octokit/rest" within my project up until the latest v20.0.1 release. 

Specific URL in question is [https://blakedarrow.github.io/DarrowRecipes/submit.html](https://blakedarrow.github.io/DarrowRecipes/submit.html)

### Versions

Octokit v.20.0.1

### Relevant log output

```shell
/*
 * [Package Error] "@octokit/core@v5.0.0" could not be built. (Imported by "@octokit/rest").
 *
 *   [1/5] Verifying package is valid…
 *   [2/5] Installing dependencies from npm…
 *   [3/5] Building package using esinstall…
 *   Running esinstall...
 *   Failed to load node_modules/@octokit/core/dist-web/index.js
 *     Unexpected token (13:9) in @octokit/core/dist-web/index.js
 *   Install failed.
 *   Install failed.
 *
 * How to fix:
 *   - If you believe this to be an error in Skypack, file an issue here: https://github.com/skypackjs/skypack-cdn/issues
 *   - If you believe this to be an issue in the package, share this URL with the package authors to help them debug & fix.
 *   - Use https://skypack.dev/ to find a web-friendly alternative to find another package.
 */
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wolfy1339** [comment]
We don't recommend people use Skypack anymore, as it's no longer maintained.

Instead we recommend ESM.sh

Can you try that and see if it resolves the issue?
