### ISSUE TITLE
setLabels probabilistic problems

### ISSUE THREAD

**Issue by xrkffgg** [octokit/rest.js#34]
**Checklist**

- [x] I checked [all open bugs](https://github.com/octokit/rest.js/issues?q=is%3Aissue+label%3Abug) and none of them matched my problem.

**Environment**

- [ ] https://api.github.com
- [ ] GitHub Enterprise Server: 
- [ ] GitHub Enterprise Cloud
- [ ] Node.js
- [ ] Browsers: 
- [ ] Others: 

`"@octokit/rest": "^18.0.12"`

**Versions**

**What happened?**

ref: https://github.com/xrkffgg/test-ci/issues/56 https://github.com/xrkffgg/test-ci/issues/55

When I execute setLabels, there is a chance that the following phenomena will occur, most cases are normal.

![image](https://user-images.githubusercontent.com/29775873/104280473-f421d000-54e6-11eb-86e3-dfdc3041570f.png)

![image](https://user-images.githubusercontent.com/29775873/104280523-08fe6380-54e7-11eb-85c4-ffadf78d723c.png)

**What the problem might be**

> [setLabels](https://docs.github.com/en/free-pro-team@latest/rest/reference/issues#set-labels-for-an-issue): Removes any previous labels and sets the new labels for an issue.

There are 2 steps to remove and add. In this two-step operation, there should be some problems, resulting in some confusion in the order of adding and removing.

**Comment by gr2m** [comment]
Sorry that you didn't get a response on the forum yet. They likely forwarded it to support and filed an internal issue for it, but probably won't report back when the problem will be resolved. 

I'll close the issue here since there is nothing actionable for us to do
