### ISSUE TITLE
octokit.actions.createWorkflowDispatch throws HttpError: Not Found everytime

### ISSUE THREAD

**Issue by meetmangukiya** [octokit/rest.js#37]
I have not got one successful api call, not even with curl, not sure why! Tried like 20-30 times with different variants, etc. 

**Checklist**

- [x] I checked [all open bugs](https://github.com/octokit/rest.js/issues?q=is%3Aissue+label%3Abug) and none of them matched my problem.

**Environment**

- [x] https://api.github.com
- [ ] GitHub Enterprise Server: 
- [ ] GitHub Enterprise Cloud
- [x] Node.js
- [ ] Browsers: 
- [ ] Others: 

**Versions**

├── @octokit/rest@18.5.2

**What happened?**

```
HttpError: Not Found
    at .../.github/workflows/node_modules/@octokit/request/dist-src/fetch-wrapper.js:49:31
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
error Command failed with exit code 1.
```

**Minimal test case to reproduce the problem**

```ts
import { Octokit } from '@octokit/rest'

(async () => {
	const octokit = new Octokit({ auth: "***" })
	const owner = 'owner'
	const repo = 'repo'
	const workflow_id = 7589211
	const ref = 'main'
	await octokit.actions.createWorkflowDispatch({
		owner,
		repo,
		workflow_id,
		ref
	});
})()
```

**What did you expect to happen?**

For the workflow to be triggered and run.

**What the problem might be**

Maybe the api is broke 🤷 🙃

**Comment by jmclean-starburst** [comment]
Im hitting this issue as well; I can fetch via `actions.getWorkflow` with a response status of 200, but then I get a `RequestError [HttpError]: Not Found` when i attempt to `action.createWorkflowDispatch`

```
'user-agent': 'octokit-rest.js/18.7.0 octokit-core.js/3.5.1 Node.js/15.4.0 (darwin; x64)',
```

**Comment by jmclean-starburst** [comment]
FWIW - to fix this, i had to add add my bot user to the project. I have been using PATs to authenticate.

**Comment by gr2m** [comment]
If you don't add your bot user to a repository, the bots PATs won't have write access, so that makes sense.

There is nothing actionable for us to do with this issue, so I'm going to close it

**Comment by jmclean-starburst** [comment]
@gr2m not to overplay this issue...but there may be a hidden bug in all this; i was still able to run `action.getWorkflow` and specify the workflow file for workflow_id; which returned 200 - while not having added the bot to the repository. May be some security issue

**Comment by gr2m** [comment]
workflows are public, so you can access them in public repositories without having read access, just like you can access files, issues, pull requests, etc
