### ISSUE TITLE
Simple User Type doesn't have to be `null`

### ISSUE THREAD

**Issue by mlbonniec** [octokit/rest.js#38]
**Checklist**

- [x] I checked [all open bugs](https://github.com/octokit/rest.js/issues?q=is%3Aissue+label%3Abug) and none of them matched my problem.

**Environment**

- [x] https://api.github.com
- [ ] GitHub Enterprise Server: 
- [ ] GitHub Enterprise Cloud
- [x] Node.js v14.15.1
- [ ] Browsers: 
- [ ] Others: 

**Versions**

```
├── @octokit/rest@18.5.2
├── @octokit/types@6.13.0
```

**What happened?**

On the schema, located at `components['schemas']['full-repository']` (from `'@octokit/openapi-types'`), the value of `owner` can be `null`. However, a repo has to be owned, so `null` shouldn't be here.

<img width="655" alt="Capture d’écran 2021-04-18 à 01 54 08" src="https://user-images.githubusercontent.com/29955402/115129734-ff563180-9fe8-11eb-82dd-7b60de661213.png">

**Minimal test case to reproduce the problem**

**What did you expect to happen?**

`owner` should be only an object, not an `object` or `null`

**What the problem might be**
Just remove `null` from the declaration file.

**Comment by AndrewSouthpaw** [comment]
Looks like the upstream issues may have been resolved, would it be possible to resume work on this?

**Comment by wolfy1339** [comment]
Can you try the latest version of `@octokit/rest`?

The [`v10.1.2` release of `@octokit/types`]( https://github.com/octokit/openapi-types.ts/releases/tag/v10.1.2) contains the fix.
