### ISSUE TITLE
[FEAT]: High-level function for Enterprise Admin > Organizations

### ISSUE THREAD

**Issue by phuhung273** [octokit/rest.js#387]
### Describe the need

Problem: To create organization, current we have to: `octokit.request('POST /admin/organizations', body)`
Improvement: high-level function: `octokit.enterpriseAdmin.createOrganization(body)`

I've implemented this feature in my company and want to contribute.

### API Version

REST API: 2022-11-28

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wolfy1339** [comment]
Please use the https://github.com/octokit/plugin-enterprise-server.js plugin
or https://github.com/octokit/plugin-enterprise-cloud.js depending on your environment
