### ISSUE TITLE
[BUG]: log request output is not overridable

### ISSUE THREAD

**Issue by ajhenry** [octokit/rest.js#393]
### What happened?

I want to standardize all my outputs to be JSON so that log processors like fluentbit will be able to consume them and format them properly.

I briefly looked but it looks like because we are using `@octokit/plugin-request-log`, it will always pretty print to the console when I want to actually print JSON. 

https://github.com/octokit/rest.js/blob/4bd9ba4fe79c6da0a0baf72bef3246c2cca6b644/src/index.ts#L10

For example, when DEBUG mode is enabled, it will always print a formatted string like this:

```
DEBUG (octokit): GitHub request: PUT https://api.github.com/repos/example/example/branches/main/protection - 200
    enforce_admins: true
    required_pull_request_reviews: {
      "dismiss_stale_reviews": true,
      "require_code_owner_reviews": false,
      "required_approving_review_count": 1,
      "dismissal_restrictions": {
        "users": [],
        "teams": []
      }
    }
    required_status_checks: null
    restrictions: null
```

And this breaks processors that split inputs based on lines

### Versions

Node v18.16.1

"@octokit/auth-app": "6.0.1"
"@octokit/auth-token": "4.0.0"
"@octokit/rest": "20.0.2"
"@octokit/types": "12.4.0"

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by wolfy1339** [comment]
If you simply use `@octokit/core` and the different plugins that make up `@octokit/core` (excluding `@octokit/plugin-request-log`)

You will get the same experience in the end without logging to the console.

A plugin could be written for logging for your JSON format.

**Comment by ajhenry** [comment]
That's actually a fantastic idea! Thanks @wolfy1339

**Comment by ajhenry** [comment]
Ah so one problem with this is that this package is used by Probot downstream for its internal octokit and AFAIK that is not overridable 🤔

**Comment by wolfy1339** [comment]
Are you sure? I just double checked probot and it doesn't seem to use the `@octokit/rest` package.

You can definitely add plugins to Probot, though it's not that simple, see https://github.com/probot/probot/issues/1477#issuecomment-778409648 for how to do it

**Comment by ajhenry** [comment]
Something is still logging requests and admittedly it’s a bit hard to track down. I’ll see if I can follow the trace. It definitely seems probot is the one logging requests from its octokit instance.

I’d even take being able to disable logging entirely from that package. Ill see if that’s possible there

**Comment by ajhenry** [comment]
Found it: https://github.com/probot/probot/blob/master/src/octokit/octokit-plugin-probot-request-logging.ts

**Comment by wolfy1339** [comment]
Better to make an issue over there then.
