### ISSUE TITLE
[BUG]: HttpError: Failed to fetch (CORS policy)

### ISSUE THREAD

**Issue by mchestnut** [octokit/rest.js#397]
### What happened?

We are seeing sporadic POST requests using octokit/rest.js failing. The requests come back with the error `HttpError: Failed to fetch` and `Access to fetch at 'https://api.github.com/repos/ChapmanAutoGroup/sites.retail/git/trees' from origin [our site] has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

We're calling the `git.createTree` and `git.createBlob` methods. We have seen it fail on either one at different times.

We've also noticed that attempting the same exact request using the same headers and payload will eventually result in a success, although the number of retries can vary from 1 to over a dozen.

The library is being using in a Vue app. We've seen the error running both locally and on a production server.

Any ideas what is causing the CORS issue?

### Versions

node: 18.17.1
@octokit/rest: 20.0.2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wolfy1339** [comment]
This seems more like a GitHub infrastructure issue than an issue with Octokit itself

**Comment by cscheffauer** [comment]
experiencing the same - can someone have a look at this?

**Comment by wolfy1339** [comment]
Please raise this issue with GitHub.

CORS issues are server-side, not client-side.

There is nothing we can do. It's GitHub that has not set the required header.
