### ISSUE TITLE
Add filtering by `head_sha` in /repos/{owner}/{repo}/actions/workflows/{workflow_id}/runs

### ISSUE THREAD

**Issue by alita-moore** [octokit/rest.js#42]
**What’s missing?**

Ability to filter by `head_sha` when making a request to [`GET /repos/{owner}/{repo}/actions/workflows/{workflow_id}/runs`](https://docs.github.com/en/rest/reference/actions#list-workflow-runs)

**Why?**

I want to see the status of my workflows for the head commit and the best I can do right now is filter by branch, event type, and status to get what I'm looking for. I then have to do an `Array.filter(..)` to get the data that I'm looking for. It would be more reliable to just be able to query for the `head_sha` in the request

**Alternatives you tried**

As described above, it works if you just get all the workflows on a given branch (PR) and find the workflow runs that have a `head_sha` that matches the PR `head_sha`.

**Comment by gr2m** [comment]
Hi @alita-moore 👋🏼 

you are asking for an addition to GitHub's REST API, there is currently no such feature. There is nothing we can do about that here with `@octokit/rest`. The best place to ask for this feature is https://github.community/c/github-ecosystem/37, there is support staff monitoring these forums, and they can forward the request to the right team at GitHub.

Hope that helps, sorry that I can't do anything more to help myself
