### ISSUE TITLE
How to create an empty commit?

### ISSUE THREAD

**Issue by jisaacks** [octokit/rest.js#427]
I just want to create a commit using Octokit, add a commit message, and put this commit on a remote branch.

Basically I want to simulate this:

```
git checkout -b myBranch origin/myBranch
git commit --allow-empty -m "my commit message"
git push origin myBranch:myBranch
```

But obviously I want to keep my local working tree intact and not have to check out a branch locally.

Can this be done?

**Comment by wolfy1339** [comment]
This post on Stackoverflow: https://stackoverflow.com/questions/11801983/how-to-create-a-commit-and-push-into-repo-with-github-api-v3 will guide you.

These are the relevant Octokit docs: https://octokit.github.io/rest.js/v20#git
