### ISSUE TITLE
[FEAT]: API to get issue comments by author

### ISSUE THREAD

**Issue by devurandom** [octokit/rest.js#440]
### Describe the need

I would like to list all comments by a certain author on a certain issue / PR.

I access the GitHub API via `actions/github-script@v7` in a GitHub Action. The `github.rest.issues.listComments` function currently only supports filtering by time (`since`), but not by author: https://octokit.github.io/rest.js/v20#issues-list-comments

### SDK Version

actions/github-script@v7

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wolfy1339** [comment]
Unfortunately this isn't the proper place for feature requests for the GitHub API.
This package only wraps the API into helper methods with no custom code on top.

https://github.com/orgs/community/discussions/categories/api-and-webhooks is the proper place to request new API features

**Comment by devurandom** [comment]
Thanks! I created a request for this: https://github.com/orgs/community/discussions/131980
