### ISSUE TITLE
[BUG]: octokit.dependabot.listAlertsForRepo does not respect severity

### ISSUE THREAD

**Issue by kunalnagar** [octokit/rest.js#458]
### What happened?

Calling `octokit.dependabot.listAlertsForRepo` with a severity filter does not respect the passed in value. For e.g:

```
const response = await octokit.dependabot.listAlertsForRepo({
  owner: repositoryOwner,
  repo: repositoryName,
  state: 'open',
  severity: 'low',
  ecosystem: 'npm',
  per_page: 10,
})
```

returns a list of ALL severities, and not just `low`

<img width="1318" alt="image" src="https://github.com/user-attachments/assets/b428ad2d-cddf-490d-9216-54568bac7123">

### Versions

Octokit.js 20.0.2 or even the latest 21.0.1
Node.js 20

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wolfy1339** [comment]
We don't do anything specific with parameters. Every parameter that is defined in the code gets sent.

Can you reproduce the issue if you send the request manually using `octokit.request()`?

**Comment by kunalnagar** [comment]
@wolfy1339 

> Can you reproduce the issue if you send the request manually using octokit.request()?

Yep, same result using `octokit.request()` as well:

```js
const response = await octokit.request(
  'GET /repos/{owner}/{repo}/dependabot/alerts',
  {
    owner: repositoryOwner,
    repo: repositoryName,
    state: 'open',
    severity: 'low',
    ecosystem: 'npm',
    per_page: 10,
  },
)
```

> Has this parameter been added recently?

Don't think so. I see it in the [REST API](https://docs.github.com/en/rest/dependabot/alerts?apiVersion=2022-11-28#list-dependabot-alerts-for-a-repository) as well as in the `20.0.2` version of `octokit/rest`

Context:
I was made aware of this issue via this [GitHub action I maintain](https://github.com/kunalnagarco/action-cve/issues/186). [Folks there seem to think](https://github.com/kunalnagarco/action-cve/issues/186#issuecomment-2208894518) it may be related to the way `getInput` works on actions/toolkit but I was able to repro it in a non-actions environment (running locally) as well.

**Comment by kunalnagar** [comment]
@kfcampbell @wolfy1339 - I did a bit more debugging and it seems that the culprit is the `ecosystem` key. If I pass in an empty string to `ecosystem`, it does not respect the `severity` param it seems. Hope this helps!


https://github.com/user-attachments/assets/e17c3a27-5f96-4bcd-abd4-af4ca16685c2

**Comment by wolfy1339** [comment]
Try reporting it over in https://github.com/orgs/community/discussions/categories/api-and-webhooks

This doesn't seem like an issue with octokit

**Comment by kunalnagar** [comment]
@wolfy1339 - created: https://github.com/orgs/community/discussions/134561

Closing this issue out. Thank you for pointing me in the right direction 👍
