### ISSUE TITLE
[FEAT]: allow issue Type management via the REST API client

### ISSUE THREAD

**Issue by jeherve** [octokit/rest.js#466]
### Describe the need

GitHub recently introduced "Issue Types", a new way to categorize and filter issues per type.

The change was announced in [this blog post](https://github.blog/changelog/2024-10-01-evolving-github-issues-public-beta/), and is detailed in https://github.com/orgs/community/discussions/139933

It is already possible to add a type to an issue via the GraphQL API:  there is an `IssueType` object to manage issue types at the organization level to create, update, and delete them. 

It would be nice if a similar option was added to the REST API Client, as part of `issues`.

### SDK Version

No

### API Version

No

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wolfy1339** [comment]
Blocked by https://github.com/octokit/openapi/pull/452

**Comment by wolfy1339** [comment]
in the meantime, you can manually use the endpoint with `octokit.request()`

**Comment by wolfy1339** [comment]
Coming back to this, it seems you are wanting new features on the REST endpoint.
Octokit is simply wrapping the requests.

You can request new features here:
https://github.com/orgs/community/discussions/categories/api-and-webhooks

**Comment by jeherve** [comment]
Good point. I started a new discussion here:
https://github.com/orgs/community/discussions/140874

I'll come back here once the option is available in the API, and then maybe we can add a new wrapper for it in Octokit.
