### ISSUE TITLE
[MAINT]: v20 uses deprecated API

### ISSUE THREAD

**Issue by skelouse** [octokit/rest.js#471]
### Describe the need

Deprecation: [@octokit/request-error] `error.code` is deprecated, use `error.status`.
Deprecation: [@octokit/request-error] `error.headers` is deprecated, use `error.response.headers`.

### API Version

20.1.1

### Relevant log output

```shell
Deprecation: [@octokit/request-error] `error.code` is deprecated, use `error.status`.
Deprecation: [@octokit/request-error] `error.headers` is deprecated, use `error.response.headers`.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wolfy1339** [comment]
This is known and fixed in v21

**Comment by skelouse** [comment]
@wolfy1339

No CJS support on v21 https://github.com/orgs/octokit/discussions/68

**Comment by wolfy1339** [comment]
The deprecated api is known in v20. It can't be fixed without breaking changes
