### ISSUE TITLE
Incompatible Octokit type in 18.5.4

### ISSUE THREAD

**Issue by tmatsuo** [octokit/rest.js#54]
**Checklist**

- [x] I checked [all open bugs](https://github.com/octokit/rest.js/issues?q=is%3Aissue+label%3Abug) and none of them matched my problem.

**Environment**

- [x] https://api.github.com
- [x] Node.js: 12

**Versions**
18.5.4

**What happened?**
We develop common library that depends on `@octokit/rest`, which has `@octokit/rest` locked to a version "18.5.2". Some functions have `Octokit` type as an argument. Today I got type error in one of our application that depends on the common library, when trying to pass Octokit instance.

```
Argument of type 'Octokit & void & { paginate: PaginateInterface; } & RestEndpointMethods & Api & API' is not assignable to parameter of type 'Octokit & void & { paginate: PaginateInterface; } & RestEndpointMethods & Api'
```

**Minimal test case to reproduce the problem**

**What did you expect to happen?**

I don't expect type incompatibility between micro versions (or even minor versions).

**Comment by gr2m** [comment]
sorry @tmatsuo I've totally missed your issue! I don't know what happened, there were a few others I missed.

Can you please provide me a minimal test case to reproduce the problem betweent 18.5.3 & 18.5.4?

> I don't expect type incompatibility between micro versions (or even minor versions).

we don't consider type changes in our semantic versioning, it's unmaintainable, and type changes do not affect production code, only your build environment. We do our best to avoid these issues, but we make no promises, unlike for actual code behavior

**Comment by tmatsuo** [comment]
@gr2m Ah got it. It's little bit inconvenient, but understood. We'll find a solution somehow.

For reproducing, it's kind of cumbersome. It also involves Probot.

Anyways, now we know types are incompatible between microversions. We'll figure it out.
