### ISSUE TITLE
Octokit typing slightly broken on TS 4.3

### ISSUE THREAD

**Issue by angelsl** [octokit/rest.js#62]
**Checklist**

- [x] I checked [all open bugs](https://github.com/octokit/rest.js/issues?q=is%3Aissue+label%3Abug) and none of them matched my problem.

**Environment**

- [ ] https://api.github.com
- [ ] GitHub Enterprise Server: 
- [ ] GitHub Enterprise Cloud
- [x] Node.js
- [ ] Browsers: 
- [x] Others: TypeScript 4.3

**Versions**

18.5.6

**What happened?**

```ts
import { Octokit } from "@octokit/rest";

function test(a?: Octokit) {
  if (a === undefined) {
    return;
  }
  // `a` is now narrowed to `never`

  const r = a.repos; // typechecking fails as `never` has no property `repos`
}
```

[Playground link](https://www.typescriptlang.org/play?target=3&ts=4.3.2&ssl=9&ssc=2&pln=1&pc=1&strict=false#code/JYWwDg9gTgLgBAbzgeQMYwga2PAvnAMyghDgCIABCdLHAeigFMBnGMgbgChOCBXAO3TAI-ODBYwAFAEMA-AC4UNbDACUiTnDjACcGXAC8RuAIAmjAsH6NT6hJq1wmMXlH5ctubltQjWTwzhpADomSGYuXCA)

This only happens in TS 4.3.

**What should happen**: `a` should not be narrowed to `never`

I suspect it is due to the type of `Octokit` being an intersection with `void`:

```ts
type Octokit = Core & void & {
    paginate: any;
} & RestEndpointMethods & Api
```

**Comment by gr2m** [comment]
I think this is a duplicate for https://github.com/octokit/octokit.js/issues/2115, can we track it there?

**Comment by angelsl** [comment]
Yeah, it is. Sorry, should've looked there too.

**Comment by gr2m** [comment]
no worries, you could not have known
