### ISSUE TITLE
This dependency was not found when running 'npm run build'

### ISSUE THREAD

**Issue by PiwanSama** [octokit/rest.js#65]
**Checklist**

- [ ] I checked all dev support sites and no one seems to have run into this problem

**Environment**

- [ ] Browsers: Google Chrome Version 91.0.4472.77
- [ ] Others: @vue/cli 4.4.6

**What happened?**

I am using O'Reily's Vue.js 3 By Example that includes OctoKit in Chapter 2. 

1. Created an Octokit mixin as below:

```
import { Octokit } from "https://cdn.skypack.dev/@octokit/rest";

export const octokitMixin = {
  methods: {
    createOctokitClient() {
      return new Octokit({
        auth: localStorage.getItem("github-token"),
      });
    }
  }
}
```

2.  Ran the command `npm run build` and receive the error below:

```
This dependency was not found:

* https://cdn.skypack.dev/@octokit/rest in ./src/mixins/octokitMixin.js

To install it, you can run: npm install --save https://cdn.skypack.dev/@octokit/rest
```

**Minimal test case to reproduce the problem**

Run the command 'npm run build' when using the browser version of Octokit

**What did you expect to happen?**

Import the package from the CDN that it is served from to get access to the GitHub REST API

**Comment by gr2m** [comment]
Hi Samalie!

The import from https://cdn.skypack.dev/@octokit/rest is meant for direct browser usage, for use cases when you have a static HTML file, without any build step.

If you use view, you have a build step. In that case you want to install the npm package.

Could you please try the following

1. Install the package through npm: `npm install @octokit/rest`
2. Replace `import { Octokit } from "https://cdn.skypack.dev/@octokit/rest";` with `import { Octokit } from "@octokit/rest";`

Now run `npm run build` again. Does the error go away?

**Comment by PiwanSama** [comment]
It worked perfectly, thank you!
