### ISSUE TITLE
pulls.update: Change pull-request draft status

### ISSUE THREAD

**Issue by peaceiris** [octokit/rest.js#69]
**What’s missing?**

[The `pulls.create` has the `draft` parameter in v5.3.1](https://github.com/octokit/plugin-rest-endpoint-methods.js/blob/v5.3.1/docs/pulls/create.md), but the `pulls.update` does not have that.

**Why?**

We want to change the draft status using octokit.

Related issue: https://github.com/peaceiris/actions-label-commenter/issues/436

**Alternatives you tried**

First, I apologize to maintainers. I understand that this repository is not good for this type of request. The GitHub REST API v3 will need to implement this capability before the octokit client.

**Comment by gr2m** [comment]
Did you try if setting `draft` with `pulls.update` works? Maybe it's just not documented. I'd try to do it using curl.

If it doesn't work, the best place to bring it up is https://github.com/github/rest-api-description/. That's GitHub's official OpenAPI spec, and all the methods you see in `@octokit/rest` are generated from it.

**Comment by peaceiris** [comment]
I have tried it in https://github.com/peaceiris/actions-label-commenter/pull/454, `pulls.update` seems not to have the ability to toggle pull-request draft state.

**Comment by gr2m** [comment]
I think in this case it's best to contact support at https://support.github.com/contact. It sounds like the feature is simply not yet implemented. You can also search if there is an open discussion on https://github.community/c/github-ecosystem/37 or create one there, it's more likely to be notified once the feature is implemented that way.

I'll close the issue for now as there is nothing actionable we can do on our side at this point

**Comment by peaceiris** [comment]
I have found the following previous requests and subscribed.

- [No way to update Pull Request Draft State - GitHub Ecosystem - GitHub Support Community](https://github.community/t/no-way-to-update-pull-request-draft-state/141890)
- [Github API: How to promote a PR from draft to ready for review? - GitHub Ecosystem - GitHub Support Community](https://github.community/t/github-api-how-to-promote-a-pr-from-draft-to-ready-for-review/177102/2)
