### ISSUE TITLE
Incorrect type for label properties when using `pulls.get` endpoint

### ISSUE THREAD

**Issue by devversion** [octokit/rest.js#73]
Octokit seems to generate its type definitions from the Github OpenAPI descriptions. Although if a developer currently deals with the `pulls.get` endpoint and intends to use the `labels` property from the response, he will run into an issue where the `name` property of labels is denoted as `nullable` / potentially `undefined`. This seems inconsistent with what the OpenAPI description provides:

https://github.com/github/rest-api-description/blob/main/descriptions/ghes-2.22/dereferenced/ghes-2.22.deref.json

```json

  "labels": {
    "type": "array",
    "items": {
    "type": "object",
    "properties": {
        "name": {
          "type": "string"
        },
        "description": {
          "type": "string",
          "nullable": true
        },
    }
    }
},
```

while the TS `types` show:

```ts
labels: {
    name?: string;
    description?: string | null;
}[];
```

Is this intentional, or a potential issue with how the OpenAPI descriptions are converted into TypeScript? It seems rather inconvenient to manually ensure these properties are defined, if technically as per spec, they are always defined?

**Comment by wolfy1339** [comment]
That is correct behaviour. The `description` and `name` properties are not marked as required in the OpenAPI spec.

**Comment by wolfy1339** [comment]
I believe this is the same issue as https://github.com/github/rest-api-description/issues/169 and octokit/openapi-types.ts#21

**Comment by devversion** [comment]
Interesting, thanks for the quick response! much appreciated. Obviously I'm not as familiar with the OpenAPI specification. 

Should this issue be closed then, given the spec does not explicitly denote these properties as "required"?

**Comment by devversion** [comment]
@wolfy1339 Makes sense. Thanks! I'm closing this.
