### ISSUE TITLE
Discussions REST API and clients

### ISSUE THREAD

**Issue by peaceiris** [octokit/rest.js#83]
**What’s missing?**

We are joining [the Discussions/Actions integration beta](https://github.com/github/feedback/discussions/4173#discussioncomment-875571). I have tried to use `issues.createComment` to post a comment to a discussions conversation, but it does not support discussions. Any plan to provide API client methods for discussions?

**Why?**

To automate discussions like issues with `rest.issues`.

**Alternatives you tried**

- `rest.issues`

**Comment by gr2m** [comment]
You can use `octokit.request()` until the REST API methods are defined in the OpenAPI spec at https://github.com/github/rest-api-description/. Once they get added to the OpenAPI spec, the `.rest` API gets updated automatically
